call_started:
  custom_fields:
    agent_id: str
    customer_id: str
  
call_active:
  custom_fields:
    duration_seconds: int

call_hold:
  custom_fields:
    hold_reason: str

call_refused:
  custom_fields:
    refused_reason: str

call_ended:
  custom_fields:
    end_reason: str

chat_started:
  custom_fields:
    agent_id: str
    customer_id: str

chat_message:
  custom_fields:
    message_length: int
    sentiment_score: float

chat_escalated:
  custom_fields:
    reason: str

chat_ended:
  custom_fields:
    end_reason: str

email_received:
  custom_fields:
    sender_id: str
    subject_length: int

email_processed:
  custom_fields:
    processing_time_ms: int

email_responded:
  custom_fields:
    response_time_minutes: int
    response_sentiment: float

